# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

stages:
  - build

.build_rest_alpine:
  stage: build
  script:
    - docker build --build-arg platform=aarch64 -f Dockerfile -t tcp_multiplexer:$CI_COMMIT_REF_SLUG-alpine .
  allow_failure: false
  tags:
    - docker